### ISSUE TITLE
start_url in cache.js

### ISSUE THREAD

**Issue by JerryGreen** [shadowwalker/next-pwa#120]
I've noticed some comments here:

https://github.com/shadowwalker/next-pwa/blob/0e9fb5850678a98b0ee0f96d468bd7c558006030/cache.js#L4-L8

Can you explain why `start_url` should be first, and what if I have custom `start_url` (not `/`) while having these default caching rules?

**Comment by shadowwalker** [comment]
This rule is here to adapt a common use case.

**Comment by shadowwalker** [comment]
This rule is here to fix the issue in an common use case: when the web app is visited for the first time, the app redirect the user to the login page. When the user finished login, they are redirect back to home page.

When the home page is cached using `StaleWhileRevalidate` strategy, user finished login, redirected to home page, the home page might give what it's cached, which is the content of login page. Then the flow is broken.

So it's better to change to `NetworkFirst` strategy.

Besides, there is another special case it helped to handle:

When the app is loaded for the first time, service worker is downloaded and activated, but at this point, the start-url page is not cached. If the user is offline at this time, the user won't be able to open the web app because it's not cached. So I use that information to issue a duplicate request only at first time after service worker activated only to cache it.

Why it must be first? It's just a convenience way to extract the information here:
https://github.com/shadowwalker/next-pwa/blob/0e9fb5850678a98b0ee0f96d468bd7c558006030/index.js#L62

**Comment by JerryGreen** [comment]
> When the app is loaded for the first time, service worker is downloaded and activated, but at this point, the start-url page is not cached. If the user is offline at this time, the user won't be able to open the web app because it's not cached. So I use that information to issue a duplicate request only at first time after service worker activated only to cache it.

That was a helpful insight! Thanks.
