### ISSUE TITLE
Offline does not work

### ISSUE THREAD

**Issue by kovkev** [shadowwalker/next-pwa#128]
# Summary

Let's try to reproduce this bug

# How To Reproduce

```
git clone https://github.com/shadowwalker/next-pwa
cd next-pwa/examples/offline-fallback
yarn install
yarn build
yarn start
yarn dev
```

Visit http://localhost:3000

Install the `next-pwa` PWA

Kill the `yarn dev` process

Refresh the PWA webpage or the http://localhost:3000

# Expected Behaviors

We expect to see something on the page, namely a placeholder.

# Screenshots

The webpage is blank (which is better than an unreachable host when doing the same steps in examples/next-9):

<img width="1214" alt="Screen Shot 2020-12-05 at 2 03 28 AM" src="https://user-images.githubusercontent.com/30991911/101236292-12054500-369e-11eb-811e-6e0d68cf5b2e.png">

# Additional Context

**Comment by shadowwalker** [comment]
This is by design.
Cache is mostly disable in development when you run with `yarn dev`. This is to reduce noise introduced by cache during development. For example you may want to debug a web push feature in service worker, while service worker still need to be there, but client js and html should be updated with every single change you made.
If you want to test offline, simply run `yarn start`. Once it's working, it's working in production anyway. You should be less concern about it during development.

https://github.com/shadowwalker/next-pwa/blob/27dee9535f12b887a8595c80ef3b079d0fd134a3/index.js#L233-L243

**Comment by kovkev** [comment]
Awesome, thank you!
