### ISSUE TITLE
service worker takes so long to activate pwa

### ISSUE THREAD

**Issue by Mood-al** [shadowwalker/next-pwa#287]
Hi guys i have facing some issues with next-pwa in my app 
i just wanted to add pwa as an app so users can install it in their devices and precache all pages that user has entered but it seems that next-pwa service-worker precaching all statics in my app even images and static pages (these static-data and images located in public folder) and i want to prevent this behavior because it's taking alot of user's resources plus this way isnt eficinet at all 

do you guys have any idea how i can achieve this behivour in my app?
i just want to show the app installing extention in browser once user enter my website and i dont want service-worker to precache everything i just want it to precache anything user have seen in my website
![image](https://user-images.githubusercontent.com/63562308/138163071-d495a067-ab97-48cb-8a93-b3dc743d9bee.png)

**Comment by taniibarra** [comment]
I have the same problem

**Comment by sudokzt** [comment]
I have the same problem

**Comment by upteran** [comment]
@Mood-al If i understand you right, and you'v got precached something that you don't want, you can use config params from readme, `publicExcludes` and `buildExcludes`

`buildExcludes` handle your build assets, and you can pass your own function, something like this

```
buildExcludes: [
   ({ asset, compilation }) => {
    if (asset.name.match(/static-data\/.*$/)) { 
      return true;
    }
    // ...another cases
    return false;
  },
  ...paths
]
```

to publicExcludes  you can pass all your folders from `public/` , by default it is only `public/noprecache` folder

This params used to generate configs for [`precacheAndRoute`](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#serving_precached_responses) from workbox, result you saw in your screenshot.
Perhaps, that's why this not kind of bug, you can control this behavior

**Comment by shadowwalker** [comment]
Like @upteran said, you can control what you want to precache, simply config it.
