### ISSUE TITLE
Next 9.3 -> sw.js file not generated in public folder.

### ISSUE THREAD

**Issue by ArijitDebRoy** [shadowwalker/next-pwa#35]
After adding next-pwa and its configuration in next.config.js, sw.js not generated neither in public folder nor in .next folder when I run next build or npm run build. In case of development also if I run npm run dev then sw.js generated inside .next folder.

You could check my repo. https://github.com/ArijitDebRoy/arijit

**Comment by lanzosuarez** [comment]
having the same issue

**Comment by shadowwalker** [comment]
@ArijitDebRoy Your website seems working fine now, feel free to reopen this issue if you still have problems.

**Comment by vishwasnavadak** [comment]
Not sure if it is related, We have out NextJS deployment on Azure App Services with custom server. Due to misconfigured Deployment, It did not delete sw.js and worker-*.js of previous deployments, I had to delete them manually from public directory. 

Further deployments are not copying the sw.js and worker files into public directory.
