### ISSUE TITLE
`additionalManifestEntries` gets overriden when provided.

### ISSUE THREAD

**Issue by cansin** [shadowwalker/next-pwa#39]
I am not sure if this is the expected behavior but providing `additionalManifestEntries` option to `pwa` config causes the if block at https://github.com/shadowwalker/next-pwa/blob/a84403cb89c247d7a7af6f584f24542a4bc5f931/index.js#L138 not to run, which ends up dropping all the `public` folder content. I am using that in order to add a static HTML as `additionalManifestEntries: [{ url: "offline", revision: nanoid() }],`. I could get over this problem by simply copy/pasting the if block, but I think it might make more sense if the library worked in an additive fashion for `additionalManifestEntries` option. Especially given there is already a `publicExcludes` option. @shadowwalker wdyt? Happy to work on a PR if you think this makes sense.

**Comment by shadowwalker** [comment]
@cansin Thanks for the pull request, the `additionalManifestEntries` config is coming from workbox. I'm preserve about this since it's changing behavior which people should expect the same from workbox.

**Comment by cansin** [comment]
Well but as soon as additionalManifestEntries is given as an option your overrides for the public folder gets overridden. And there is no way to get it except for copy/pasting your source code. Don’t you think that is a problem?

**Comment by cansin** [comment]
@shadowwalker ^ in case you are not getting notifications for closed issues.

**Comment by sfiquet** [comment]
I second @cansin's comment. It doesn't make sense to have to copy/paste your code in order to be able to keep the default behaviour when adding entries to the precache. You have 3 use cases but you're only catering for 2:
1. library user doesn't add precache entries: you precache the public folder, excluding the files you're generating
2. library user takes care of all the precaching: you precache nothing
3. library user wants to keep precaching the public folder in the default way and just add a number of files to precache: currently copy/pasting your code is the only way. It would be so much better to have a flag for that in the config.

**Comment by shadowwalker** [comment]
I will revisit this
