### ISSUE TITLE
How to avoid caching API requests at all?

### ISSUE THREAD

**Issue by brunocanepa** [shadowwalker/next-pwa#46]
What config should I set to avoid caching XHR api requests
I managed to doing this, so it is cached for 1 second

```
runtimeCaching: [
      {
        urlPattern: /\/api\//g,
        handler: 'NetworkFirst',
        options: {
          cacheName: 'api',
          expiration: {
            maxEntries: 1,
            maxAgeSeconds: 1 
          }
        }
      }
    ],

**Comment by shadowwalker** [comment]
I assume this is partial of your `runtimeCaching`, it will work. But there is some misunderstanding about this configuration. To help you understand it, what it does is whenever a http request send to `api` route:

1. If device have network access, it always fetch from network without using any cache
2. If device doesn't have network access and has cache for `api` route, it fetch from the cache, but if the cache is expired (1 second after stored) it will return error since the cache is invalid.
