### ISSUE TITLE
after refresh not show cached page

### ISSUE THREAD

**Issue by zahraHaghi** [shadowwalker/next-pwa#57]
hi. I am using next-pwa and every thing is ok. but when  user is offline , user can navigate between  cjacjed page but after refresh in page  **no internet error** show

**Comment by shadowwalker** [comment]
This behavior is expected.
If the user is never loading `/abc` before when online. If he goes offline, by typing `/abc` in the address bar or refresh, the browser shows no internet error because the html of this page is never cached.
However, you may wondering why if user visit `/` page, then goes offline and navigate by clicking button on your page, everything just works. That is because whenever you are using `<Link>` component from `next` or `next/router`, it does front end routing for you. There is no real HTTP request, hence the service worker is not involved here. It's just javascript changing the content on the page and the text on your browser address bar, it's "FAKE" navigation.
When you navigate to `/abc` then hit refresh button on your browser, the browser send a HTTP request to get the html for that page, the service worker will intercept the request and lookup in the cache, and nothing is found, then it tries to get from the internet. It failed because device offline.
